optimizely/python-sdk

optimizely/optimizely.py
requirements/test.txt
tests/benchmarking/benchmarking_tests.py
tests/benchmarking/data.py

Adding Benchmarking test suite

---

optimizely/event_builder.py
optimizely/helpers/enums.py
optimizely/optimizely.py
optimizely/project_config.py
tests/test_config.py
tests/test_event_builder.py

This change introduces the ability to pick appropriate event builder based on version of the datafile.
@mikeng13 @delikat @vraja2 @haleybash-optimizely

Picking appropriate event builder based on config version

---

optimizely/event_builder.py
optimizely/project_config.py
tests/test_config.py
tests/test_event_builder.py

@haleybash-optimizely @delikat @vraja2 @mikeng13

Add user attribute information to events

---

optimizely/event_builder.py
optimizely/exceptions.py
optimizely/optimizely.py
optimizely/project_config.py
tests/test_config.py

@mikeng13 @haleybash-optimizely @delikat @vraja2

Change the term "goal" to "event"

---

optimizely/event_builder.py
optimizely/project_config.py
tests/base.py
tests/helpers_tests/test_audience.py
tests/helpers_tests/test_condition.py
tests/helpers_tests/test_experiment.py
tests/helpers_tests/test_validator.py
tests/test_bucketing.py
tests/test_config.py
tests/test_event_builder.py
tests/test_optimizely.py

@delikat @vraja2 @haleybash-optimizely @mikeng13

Adding layer ID information on experiment

---

optimizely/event_builder.py
optimizely/event_dispatcher.py
optimizely/helpers/enums.py
optimizely/optimizely.py
tests/test_event_dispatcher.py
tests/test_optimizely.py

@haleybash-optimizely @delikat @vraja2 @mikeng13

Updating dispatch event 

---

.travis.yml
README.md

cc @delikat @haleybash-optimizely @vraja2 @mikeng13

Adding travis CI

---

optimizely/helpers/constants.py
optimizely/helpers/validator.py
optimizely/project_config.py
tests/base.py
tests/helpers_tests/test_validator.py
tests/test_optimizely.py

@haleybash-optimizely @mikeng13 @vraja2 @delikat

Update JSON validation for v2 endpoint

---

optimizely/project_config.py
tests/test_config.py

@vraja2 @haleybash-optimizely @mikeng13 @delikat

Updating track event to work for grouped experiments

---

optimizely/bucketer.py
optimizely/entities.py
optimizely/event_builder.py
optimizely/helpers/audience.py
optimizely/helpers/experiment.py
optimizely/optimizely.py
optimizely/project_config.py
tests/helpers_tests/test_audience.py
tests/helpers_tests/test_experiment.py
tests/test_bucketing.py
tests/test_config.py
tests/test_event_builder.py
tests/test_optimizely.py

Change for Experiment, Attribute and Event
@vraja2 @delikat @haleybash-optimizely @mikeng13

Changing to use objects

---

optimizely/bucketer.py
optimizely/entities.py
optimizely/exceptions.py
optimizely/project_config.py
tests/base.py
tests/test_config.py

@delikat @haleybash-optimizely @vraja2

Moving groups to object

---

optimizely/helpers/experiment.py
optimizely/optimizely.py
tests/helpers_tests/test_experiment.py
tests/test_optimizely.py

@vraja2 @haleybash-optimizely @delikat

Updating whitelisting check to precede audience check

---

CONTRIBUTING.md

@haleybash-optimizely @delikat @vraja2 @mikeng13

Updating contribution doc to use CLA

---

optimizely/event_builder.py
optimizely/exceptions.py
optimizely/helpers/enums.py
optimizely/helpers/validator.py
optimizely/optimizely.py
optimizely/project_config.py
tests/test_event_builder.py
tests/test_optimizely.py

@vraja2 @haleybash-optimizely @delikat @mikeng13

Better exception handling in the SDK

---

README.md

fix developer docs link

---

optimizely/optimizely.py
tests/test_optimizely.py

Fixing logger

---

optimizely/entities.py

Fix parsing of v1 file

---

CHANGELOG.md
CONTRIBUTING.md
README.md
optimizely/bucketer.py
optimizely/entities.py
optimizely/event_builder.py
optimizely/event_dispatcher.py
optimizely/exceptions.py
optimizely/helpers/audience.py
optimizely/helpers/enums.py
optimizely/helpers/experiment.py
optimizely/helpers/validator.py
optimizely/optimizely.py
optimizely/project_config.py
optimizely/version.py
setup.py
tests/base.py
tests/helpers_tests/test_audience.py
tests/helpers_tests/test_experiment.py
tests/test_bucketing.py
tests/test_config.py
tests/test_event_builder.py
tests/test_event_dispatcher.py
tests/test_optimizely.py

Bump to version 1.0.0

---

optimizely/event_builder.py
optimizely/optimizely.py
optimizely/project_config.py
tests/test_config.py
tests/test_event_builder.py
tests/test_optimizely.py

Add revision information to log events

---

CONTRIBUTING.md
README.md
tests/base.py
tests/test_bucketing.py
tests/test_event_builder.py

Add tests for empty entity ID in experiment traffic allocation

---

CONTRIBUTING.md
optimizely/bucketer.py
optimizely/decision_service.py
optimizely/entities.py
optimizely/event_builder.py
optimizely/helpers/experiment.py
optimizely/helpers/validator.py
optimizely/optimizely.py
optimizely/project_config.py
optimizely/user_profile.py
tests/helpers_tests/test_experiment.py
tests/helpers_tests/test_validator.py
tests/test_bucketing.py
tests/test_config.py
tests/test_decision_service.py
tests/test_event_builder.py
tests/test_optimizely.py
tests/test_user_profile.py

@optimizely/fullstack-devs
Merging this in so we can get rid of `devel`

Merge devel into master

---

optimizely/entities.py
optimizely/project_config.py
tests/base.py
tests/test_config.py

Add feature flag parsing

---

optimizely/bucketer.py
optimizely/decision_service.py
optimizely/optimizely.py
tests/base.py
tests/test_decision_service.py
tests/test_optimizely.py

Add is_feature_enabled API method

---

optimizely/user_profile.py
tests/test_optimizely.py

Fixing test relying on ordering

---

optimizely/event_builder.py
tests/test_event_builder.py

- Attributes list should always be included
- Removed revision number

Updated event_builder

---

optimizely/entities.py
optimizely/project_config.py
tests/test_config.py

Remove earlier feature flag parsing

---

optimizely/decision_service.py
optimizely/optimizely.py
tests/test_decision_service.py
tests/test_optimizely.py

Preventing events from being sent when user is part of a rollout

---

optimizely/helpers/event_tag_utils.py
tests/helpers_tests/test_event_tag_utils.py

✏️ Fixed event tag utils tests

Event Tag Utils Tests Edit

---

optimizely/bucketer.py
optimizely/decision_service.py
tests/test_bucketing.py
tests/test_decision_service.py
tests/test_optimizely.py

Introduce bucketing ID in Python SDK

---

requirements/core.txt

Updating mmh3 for Python to handle Windows 10 installation issues

---

.github/pull_request_template.rst
CONTRIBUTING.rst

**Summary**
- Adds commit message guidelines in CONTRIBUTING.rst.
- Adds PR template for Github PRs.

chore(contrib): Add PR template and commit message guidelines.

---

optimizely/event_builder.py
optimizely/optimizely.py
tests/test_event_builder.py
tests/test_optimizely.py

Summary
-------
This change updates track to always send an event without doing experiment/variation lookup. 
Test plan
---------
- Updated unit tests.
- (Pending) Manual tests confirming that even with decisions, conversions are recorded fine.
- (Pending) SDK compatibility tests.

feat(track): Introducing easier event tracking

---

README.rst

Summary
-------
- Fix the markdown formatted links to be rst formatted links.

fix(docs): Update README.rst

---

optimizely/config_manager.py

Summary
-------
Logger in config_manager was being initialized incorrectly. Fixing that.

Fixing issue in logger

---

.travis.yml

Summary
-------
SDK_BRANCH should be passed to script

fix(ci): branch should be passed

---

CHANGELOG.rst
README.rst
optimizely/version.py

Preparing for 3.2.0 beta release. Also, includes changes from https://github.com/optimizely/python-sdk/pull/188

chore(release): Preparing for 3.2.0-beta release

---

CHANGELOG.md

chore: make changelog conform to standard format

---

optimizely/config_manager.py
optimizely/helpers/enums.py
tests/test_config_manager.py

Summary
-------
Replica of https://github.com/optimizely/python-sdk/pull/208
208 was merged in a branch that is no more applicable. Please merge this one
Test plan
---------
Issues
------
-  “THING-1234” or “Fixes #123”

fix(config-manager): Updated polling interval condition. 

---

optimizely/event/event_factory.py
optimizely/helpers/event_tag_utils.py

Fixing log messages for numeric metric

---

CHANGELOG.md

Summary
-------
Thanks to @emielrv for reporting and figuring out the issue
Issues
------
Fixes https://github.com/optimizely/python-sdk/issues/220

fix(install): Updating message to fix installation issues 

---

CHANGELOG.md
optimizely/version.py

chore: prepare for release 3.4.0

---

requirements/core.txt

Issues
------
-  Fixes https://github.com/optimizely/python-sdk/issues/232

chore: Updating jsonschema to 3.2.0

---

CHANGELOG.md
optimizely/version.py

Release to address one of the issues in #232

chore(release): Preparing for 3.4.1 release

---

requirements/docs.txt

Summary
-------
- Added docs.txt to requirements for setting up sphinx
Test plan
---------
Issues
------
-  OASIS-6103

Sphinx setup

---

docs/source/bucketing_algorithm.rst
docs/source/config_manager.rst
docs/source/optimizely_config.rst

Summary
-------
Remove private methods from sphinx docs
Test plan
---------
None
Issues
------
-  OASIS-6181

Remove private methods from sphinx docs

---

CONTRIBUTING.md
README.md
docs/source/api_reference.rst
docs/source/bucketing_algorithm.rst
docs/source/conf.py
docs/source/index.rst
docs/source/readme.rst

Summary
-------
-  Update docs title to “Optimizely Python SDK”.
-  Include README to table of contents to have it broken up into individual sections.
-  Fix URL in “Please see CONTRIBUTING”.
-  Remove Event Builder since it is not a customer facing concept.
-  Rename “Bucketing Algorithm Methods” —> “Bucketing”.
-  In Pull request acceptance criteria, update PEP-8 to Flake8.
-  Under “Style", the message is changed to “We enforce Flake8 rules." since the link to tox.ini is no longer working.
Test plan
---------
None.
Issues
------
OASIS-6317

Update sphinx docs per OASIS-6317

---

README.md

Summary
-------
- Fix table formatting
- Fix `PollingConfigManager` anchor
Test plan
---------
None
Issues
------
OASIS-6317

[OASIS-6317] - Fix README.md format

---

docs/source/conf.py

Summary
-------
Specified master_doc for ReadTheDocs html build.
Test plan
---------
None
Issues
------
OASIS-6103

Specify master_doc for ReadTheDocs html build

---

.readthedocs.yml

Summary
-------
Creating Read the Docs config file for sphinx docs

feat(docs): Creating Read the Docs config file for Sphinx Docs

---

.readthedocs.yml
requirements/docs.txt

Updating it this way to avoid duplicating dependencies

chore(deps): Updating docs dependencies based on core dependencies

---

CHANGELOG.md
optimizely/version.py

Bringing in changes from 3.4.x to master.

chore(release): Bump version in master

---

optimizely/optimizely_config.py
optimizely/project_config.py
tests/test_config.py
tests/test_optimizely_config.py

Summary
-------
- Add datafile accessor methods/functionalities
Testing
-------
- Ran manual tests

feat: add datafile accessor

---

.travis.yml

This PR hooks Fullstack Prod Suite build on Travis.
Added FPS Check which should be passed

ci: hook fullstack-prod-suite on travis

---

CHANGELOG.md
optimizely/version.py

Summary
-------
Preparing for release.
Test plan
---------
Unit tests pass.

chore: Preparing for 3.6.0 release

---

optimizely/event/event_factory.py

Summary
-------
- fixing metadata and decision payload

fix: correcting metadata and decision payload

---

CHANGELOG.md
optimizely/version.py

Summary
-------
-  Prepare for 3.10.0 Release

chore: Prepare for 3.10.0 Release

---

optimizely/optimizely_user_context.py

Summary
-------
-  Forced decision logging updated to info from debug.
Test plan
---------
- All testcases and FSC should pass.

feat: Debug logging changed to info

---

.github/workflows/integration_test.yml
.github/workflows/python.yml

- Git actions updated to run FSC on git actions.
- Need to change travisci-tools branch from `mnoman/gitActions` to `master`

feat: updated for fsc git action

---

.github/workflows/python.yml
README.md

Summary
-------
-  Switch build badge from travis to github actions

docs: fix readme badge

---

optimizely/odp/odp_config.py
optimizely/odp/odp_event.py
tests/test_odp_config.py

Summary
-------
Config for managing odp integration
Test plan
---------
- added test_odp_config.py
Ticket
---------
[OASIS-8405](https://optimizely.atlassian.net/browse/OASIS-8405)
[OASIS-8442](https://optimizely.atlassian.net/browse/OASIS-8442)

feat: add odp config

---

CHANGELOG.md

Summary
-------
-  Add description of PollingConfigManager breaking change to the changelog under Unreleased header.
Ticket
------
[FSSDK-8773](https://jira.sso.episerver.net/browse/FSSDK-8773)

chore: update Changelog with pollingconfig breaking change

---

optimizely/odp/odp_event_manager.py

Summary
-------
-  When flush_interval is zero, set batch_size to 1.
Test plan
---------
All tests pass
Ticket
------
-  [FSSDK-8804](https://jira.sso.episerver.net/browse/FSSDK-8804)

fix: change batch_size from 0 to 1

---

CHANGELOG.md
README.md
optimizely/version.py
setup.py

Summary
-------
- Prepare for 4.1.1 release
Ticket
------
[FSSDK-8954](https://jira.sso.episerver.net/browse/FSSDK-8954)

[FSSDK-8954] chore: prep 4.1.1

---

optimizely/helpers/enums.py
optimizely/odp/odp_segment_api_manager.py
tests/test_odp_segment_api_manager.py

Summary
-------
Change invalid identifiers error code to match ODP.
Test plan
---------
all  tests pass
Ticket
------
[FSSDK-9129](https://jira.sso.episerver.net/browse/FSSDK-9129)

[FSSDK-9129] fix: invalid identifiers error code

---

CHANGELOG.md
optimizely/version.py

Summary
-------
-  Update changelog and version for advanced audience targeting
Issues
------
-  [FSSDK-9107](https://jira.sso.episerver.net/browse/FSSDK-9107)

[FSSDK-9107] Update changelog and version for advanced audience targeting

---

.github/workflows/python.yml
requirements/docs.txt
requirements/typing.txt

Summary
-------
-  Updating old dependencies
Test plan
---------
- All tests should pass
Issues
------
-  -  [FSSDK-9100](https://jira.sso.episerver.net/browse/FSSDK-9100)

[FSSDK-9100]: Updating old dependencies.

---

CHANGELOG.md
optimizely/version.py

Summary
-------
-  Prep for patch release 5.0.1, update changelog, update version
Test plan
---------
Issues
------
- [FSSDK-10317](https://jira.sso.episerver.net/browse/FSSDK-10317)

[FSSDK-10317]

---

CHANGELOG.md
optimizely/version.py

Summary
-------
-  Add changelog
- Update version number
Test plan
---------
N/A
JIRA
----
- [FSSDK-11212](https://jira.sso.episerver.net/browse/FSSDK-11212)

[FSSDK-11212] chore: Prepare for 5.2.0 release
