requirements/core.txt
This patch removes some unused requirements and unpins the versions of the other core dependencies to avoid conflicting with code in other applications.
I suspect the remaining dependencies could be made more flexible, but unpinning requests was my main concern.
=> Cleanup dependencies

optimizely/event_builder.py, optimizely/optimizely.py, tests/test_event_builder.py
This diff introduces event builder v2.
This diff does not intend to:
Redirect to builder v2 based on version (will come in a separate diff)
Look for layer ID on experiment (will come in a separate diff)
Use attributes (will come in a separate diff)
Clean up terminology (change goal --> key every place et al) - Coming in a much later diff
cc @haleybash-optimizely @delikat @vraja2 @mikeng13
=> Introducing event builder v2

optimizely/event_builder.py, optimizely/optimizely.py, optimizely/project_config.py, tests/test_config.py
@delikat @vraja2 @haleybash-optimizely @mikeng13
=> Moving Attribute and Event to namedtuples

optimizely/entities.py, optimizely/exceptions.py, optimizely/helpers/audience.py, optimizely/helpers/enums.py, optimizely/project_config.py, tests/helpers_tests/test_audience.py, tests/test_config.py
@delikat @vraja2 @haleybash-optimizely
=> Moving audiences to use object

optimizely/bucketer.py, optimizely/event_builder.py, optimizely/helpers/experiment.py, optimizely/optimizely.py, tests/helpers_tests/test_experiment.py, tests/test_bucketing.py, tests/test_event_builder.py, tests/test_optimizely.py
=> Refactor order of bucketing operations

optimizely/helpers/event_tag_utils.py, tests/helpers_tests/test_event_tag_utils.py
Caught this when I was running some numeric metric e2e tests.
=> Fixed a bug with how the numeric metric getters handle non string and number values.

optimizely/event_builder.py, optimizely/project_config.py, tests/test_event_builder.py, tests/test_optimizely.py
=> Implement IP Anonymization 

CHANGELOG.md, optimizely/version.py
=> Preparing 1.4.0 for release

optimizely/optimizely.py, optimizely/project_config.py, tests/test_config.py, tests/test_optimizely.py
Please note that we check for **'featureEnabled'** flag only in the method **'isFeatureEnabled'**. So this flag makes no difference in any of the variable accessor methods. 
The issue at hand was that variations, which have an empty **'variables'** node, didn't get included in **'variation_variable_usage_map'**. This resulted in https://github.com/optimizely/python-sdk/blob/master/optimizely/project_config.py#L435 case when detailed logs were inspected. 
**Changes in place:** 
* Generate a key for every variation in **'variation_variable_usage_map'**
* Move log message and add additional message to provide correct and verbose logs.
=> Fix feature variable accessor default value

.gitignore, README.md, optimizely/bucketer.py, optimizely/decision_service.py, optimizely/logger.py, optimizely/notification_center.py, optimizely/optimizely.py, optimizely/project_config.py, setup.py, tests/base.py, tests/test_bucketing.py, tests/test_config.py, tests/test_decision_service.py, tests/test_logger.py, tests/test_optimizely.py, tests/testapp/application.py
* Update README to reflect more modern install conventions.
* Refactor SimpleLogger/NoOpLogger to use standard python logging.
* Update tests.
=> Overhaul logging integration.

setup.py
The `long_description` was introduced recently. On publishing I noticed that formatting is all broken here: https://pypi.org/project/optimizely-sdk.
Searching on the web revealed that by default it expects text to be `rst`. Defining content type is the solution to continue using markdown format.
=> Fixing formatting of description

optimizely/event_dispatcher.py
Address issue raised [here](https://github.com/optimizely/python-sdk/issues/139)
=> fix(dispatch): Updating default event dispatcher to actually raise exceptions

optimizely/project_config.py, tests/test_config.py
Summary
-------
- Forced variation key passed as an empty String will be invalid argument.
- Updated inputs validation for set_forced_variation.
- Updated unit tests for empty string variation key.
=> fix(set_forced_variation): Treats empty variation key as invalid and does not reset forced variation.

optimizely/helpers/audience.py, optimizely/helpers/condition.py, optimizely/helpers/condition_tree_evaluator.py, optimizely/helpers/validator.py, optimizely/project_config.py, tests/base.py, tests/helpers_tests/test_audience.py, tests/helpers_tests/test_condition.py, tests/helpers_tests/test_condition_tree_evaluator.py, tests/test_config.py, tests/test_optimizely.py
Summary
-------
Audience evaluation and project config to support typedAudiences. #146 and #147 consolidated PR that should be merged in master.
=> feat (audience match types): Condition evaluator and Project Config PRs consolidation.

optimizely/helpers/validator.py, tests/base.py, tests/helpers_tests/test_condition.py, tests/helpers_tests/test_validator.py
Summary
-------
Don't target NAN, INF or -INF doubles
Don't target Values > 2^53. 
Modified is_attribute_valid to check if the number is finite. 
Test plan
---------
Issues
------
OASIS-3654
https://github.com/optimizely/python-sdk/pull/146#discussion_r237850806
=> feat(attribute_value): Don't target NAN, INF, -INF and  > 2^53

.travis.yml
Summary
-------
- Adding python3.7 support. Ubuntu Trusty does not support this version so we have to use Xenial instead.
Note
----
- If you merge this one, discard https://github.com/optimizely/python-sdk/pull/159
=> refac(ci): (adding python 3.7 support fix) only xenial for 3.7

.travis.yml, CONTRIBUTING.rst, optimizely/helpers/condition.py, optimizely/helpers/condition_tree_evaluator.py, requirements/test.txt, tests/benchmarking/benchmarking_tests.py, tests/benchmarking/data.py, tests/helpers_tests/test_audience.py, tests/test_optimizely.py, tox.ini
Summary
-------
This implements flake8 which is a wrapper over pyflakes, pycodestyle(PEP8), and circular complexity checks. 
Also, the linting stage has been separated so that it immediately fails the build rather than creating separate environments for multiple python versions and failing all the jobs for the same reason. 
Test plan
---------
Issues
------
=> ci: Replace pep8 by flake8 and separate linting stage on Travis

CHANGELOG.rst, optimizely/version.py, requirements/core.txt
Summary
-------
Bumping version number and adding release notes for 3.0.0 release
=> chore(release): Preparing for 3.0.0 release

.travis.yml
This uses the script from travisci-tools repo to trigger compat suite. 
OASIS-4389
=> ci: use travisci-tools script to trigger-fullstack-compat suite

optimizely/helpers/enums.py, optimizely/optimizely.py, tests/test_optimizely.py
Summary
-------
Implemented DecisionListener in following APIs:
- activate
- get_variation
Test plan
---------
Unit tests for DecisionListener
Issues
------
- OASIS-4350
=> feat(DecisionListener): Adds experiment decision listener.

CHANGELOG.rst
We want to _further_ clarify the event tracking changes in the 3.0 release. I'm updating the `master` branch but I won't try to update the `3.0.0` tag.
[Preview link](https://github.com/optimizely/python-sdk/blob/nikhil/update-3.0.0-changelog/CHANGELOG.rst)
=> Update the 3.0.0 changelog

optimizely/optimizely.py, tests/base.py, tests/test_config.py, tests/test_optimizely.py
- Feature variable APIs now return default variable value when featureEnabled property is false.
- Added unit tests.
=> feat(api): Feature variable APIs return default variable value when featureEnabled property is false.

optimizely/decision_service.py, optimizely/helpers/enums.py, optimizely/optimizely.py, tests/test_decision_service.py, tests/test_optimizely.py
Summary
-------
Implemented onDecisionListener in following APIs:
- is_feature_enabled
- get_enabled_features
Test plan
---------
Unit tests for DecisionListener
Issues
------
- OASIS-4351
=> feat(DecisionListener): Adds feature decision listener.

README.rst
Summary
-------
Updates the README so that it's clear the SDK is used for both FullStack and Rollouts
=> feat(rollouts): Update README for Rollouts

optimizely/decision_service.py, optimizely/helpers/enums.py, optimizely/optimizely.py, optimizely/project_config.py, tests/base.py, tests/test_config.py, tests/test_decision_service.py, tests/test_optimizely.py
- Incorporated new decision notification listener changes.
- Updated test data to fix experiment to feature relationship.
- Added unit tests for type `feature-test` and project config method.
- Updated unit tests.
=> feat(decision-listener): Incorporated new decision notification listener changes.

optimizely/bucketer.py, optimizely/decision_service.py, optimizely/event_builder.py, optimizely/optimizely.py, optimizely/project_config.py, tests/test_bucketing.py, tests/test_decision_service.py, tests/test_event_builder.py, tests/test_optimizely.py
Summary
-------
- Refactoring to pass around `ProjectConfig` vs every class having its own copy of `ProjectConfig`. This way `Bucketer`, `DecisionService` and `EventBuilder` are static and makes way for us to introduce datafile manager.
Test plan
---------
Unit tests and compatibility suite tests continue to pass.
=> Refactoring and passing ProjectConfig from Optimizely itself.

optimizely/notification_center.py, tests/test_notification_center.py, tests/test_optimizely.py
Summary
-------
`notification_center.NotificationCenter` did not have any unit tests for the class. All the related unit tests were absorbed in tests for `optimizely.Optimizely`. This PR:
- Creates `test_notification_center.py` to introduce unit tests for the `NotificationCenter` class.
- Fixes naming in the `NotificationCenter` class. This includes fixing incorrect API names which have been marked as deprecated and we will discontinue support in the next major release.
- Removes tests in `test_optimizely.py` which were focusing on tests captured in `test_notification_center.py`.
Test plan
---------
- Unit tests
=> Fixing multiple issues in notification_center.

optimizely/config_manager.py, optimizely/helpers/validator.py, tests/test_config_manager.py
Summary
-------
Handling `update_interval` values if they cause overflow or are of the invalid type.
=> Handling update_interval values.

optimizely/config_manager.py, optimizely/helpers/validator.py, optimizely/optimizely.py, tests/test_config_manager.py, tests/test_optimizely.py
Summary
-------
This change introduces `notification_center` on `optimizely.Optimizely` thereby allowing instance of it to be shared by `Optimizely` and all classes under `config_manager`. Previously, `config_manager` had its own `NotificationCenter` instance and `optimizely.Optimizely` had its own instance leading to issues.
=> Making notification_center optional for optimizely.Optimizely.

.travis.yml
Summary
-------
-  The “what”; a concise description of each logical change
-  Another change
The “why”, or other context.
Test plan
---------
Issues
------
-  “THING-1234” or “Fixes #123”
=> ci(benchmarking): Added benchmarking stage

optimizely/optimizely.py, tests/test_optimizely.py
- Implement `get_feature_variable` method to return value of variable with any type 
- Create new unit tests to ensure functionality of `get_feature_variable`
Python is a dynamically-typed language, like [JavaScript](https://github.com/optimizely/javascript-sdk/pull/298), so it suffices to have a single method return the value of a feature variable rather than have a separate method for each possible feature variable type.
- Enable gherkin integration tests for Python in FSC suite and python-testapp
- Fulfills one of the [SDK convenience APIs](https://docs.google.com/document/d/1MCsMioa4TNImryaDdOJJsZwL9j5zFvFIXODArHF3ORs/edit#) (design doc [here](https://docs.google.com/document/d/1CZ0iappDujwgQzYR8oiU9LRVzLho9jGQt2zaB1rpB48/edit#heading=h.6jynaot9cbnq))
=> Implement get_feature_variable and create unit tests

optimizely/config_manager.py, optimizely/helpers/enums.py, tests/test_config_manager.py
Summary
-------
-  Update condition for using default update_interval when polling files.
=> fix(config-manager): Updated polling interval condition.

optimizely/config_manager.py, tests/test_config_manager.py
Summary
-------
A Polling Manager unit test intermittently fails on some Python versions. 
See here: https://travis-ci.org/optimizely/python-sdk/jobs/585691111
Trying multiple approaches of using a short polling interval, using a blocking queue with a mocked side_effect, and putting a time sleep before assertion reveals that this is some issue with mocked object on pypy and pypy3 that it does not know even if it has been called many times. 
We can get rid of this assertion since we are already asserting is_running flag to ensure that the thread is running
Test plan
---------
Should pass existing unit tests. 
Issues
------
-  “THING-1234” or “Fixes #123”
=> tests: Fix intemittent multithreaded unit test failure

optimizely/config_manager.py, optimizely/helpers/enums.py, tests/test_config_manager.py
Summary
-------
This introduces blocking timeout in Python Config Manager. Config Manager will block the main thread until the config is available or the timeout occurs. 
https://github.com/optimizely/python-testapp/pull/63 should be merged to pass FSC tests for this PR.
=> feat: Add blocking timeout in polling manager

optimizely/event/event_processor.py, tests/test_event_processor.py
Summary
-------
- Fixes python 3 type error when flush interval passes as string
- Checks if self.executor is defined before calling method on it to avoid scenario where start_on_init is False and user tries to check if the processor is running or tries to stop it. 
Test plan
---------
Added unit test with flush interval passed as string
Issues
------
-  OASIS-5525
=> fix: avoid type error for Python 3

optimizely/config_manager.py, optimizely/event/event_processor.py, optimizely/optimizely.py, tests/test_config_manager.py, tests/test_event_processor.py
Summary
-------
- The polling config manager is supposed to wait until config is ready. Previously, the config will be attempted to be initialized with empty datafile. This was resolved by overriding up `_set_config` in `PollingConfigManager`.
- Config ready event had no business in `StaticConfigManager` so it has been moved from there.
- Some formatting and other miscellaneous fixes.
=> fix(Polling Manager): Fixing how config manager blocks. Miscellaneous other fixes as well.

optimizely/event/event_processor.py, tests/test_event_processor.py
It should be seconds as expected
=> fix(event flush): Setting unit of time correctly

optimizely/event/event_processor.py, tests/test_event_processor.py
Also, hang on queue with timeout at flush interval
Summary
-------
-  The deadline is not reset on the _run after the deadline has passed.  
-  get can hang with a timeout.  allow get to wait with timeout at flush interval
Test plan
---------
Current tests should pass
Issues
------
=> (fix): refactor batch_event_processor to reset deadline after it passes. 

optimizely/event/event_processor.py, tests/test_event_processor.py
Summary
-------
-  Added more logging for why flush was initiated and flush size.
- Remove reset of current_batch that was not wrapped in a lock and was necessary after a call to flush_batch.
Test plan
---------
- Augmented test for flush once to include debug message for flushing with batch size.
=> (fix): add more debug logging. remove extra current_batch set

optimizely/optimizely.py, optimizely/optimizely_config.py, tests/base.py, tests/test_optimizely.py, tests/test_optimizely_config.py
Summary
-------
Adds support for get_optimizely_config public API. 
Test plan
---------
- Tested manually with FSC OptimizelyConfig tests. 
- Added simple Unit tests in test_optimizely.py
Issues
------
-  OASIS-5464
=> feat: get_optimizely_config API

optimizely/config_manager.py, optimizely/optimizely.py, requirements/test.txt, tests/test_config_manager.py, tests/test_optimizely.py
Summary
-------
Optimizely Config cached in Config Manager. OptimizelyConfig should only be created on datafile update. Otherwise, Config Manager should return a cached copy.
Set Pyyaml version to 5.2 since the latest version 5.3 only works with Python 3.5+. And we need to run tests with Python 3.4 on Travis
Test plan
---------
- Added unit tests
Issues
------
OASIS-5791
=> feat: Cache OptimizelyConfig and set Pyyaml version

optimizely/event/event_processor.py, tests/test_event_processor.py
Summary
-------
Forwarding Event Processor should default to Default Event Dispatcher when provided None.
Currently, we catch exception with this error: 
> AttributeError: 'NoneType' object has no attribute 'dispatch_event'
Test plan
---------
- Added a unit test
Issues
------
=> fix: Forwarding Event Processor defaults to default event dispatcher

.travis.yml
Summary
-------
Add lint rule for spell checking markdown files
=> ci(travis): add mdspell

.gitignore, CONTRIBUTING.md, README.md, docs/Makefile, docs/make.bat, docs/source/conf.py, docs/source/contributing.rst, docs/source/index.rst
@aliabbasrizvi please take a look at this pr. 
Thanks!
Summary
-------
- Created script to autogenerate documentation
- Added sphinx/build to .gitignore
-  Added minor necessary changes to README.md and CONTRIBUTING.md for proper conversion to .rst
Test plan
---------
None at the moment
Issues
------
OASIS-6178
=> Create script to generate html docs with sphinx

optimizely/entities.py, optimizely/helpers/enums.py, optimizely/optimizely.py, optimizely/project_config.py, tests/base.py, tests/test_config.py, tests/test_optimizely.py, tests/test_optimizely_config.py
- implement   get_all_feature_variables and get_feature_variable_json public APIs
- created and adjusted unit tests
=> feat: Implement get_all_feature_variables and get_feature_variable_json

docs/README.md
Summary
-------
Added README.md for generating sphinx docs
Test plan
---------
None
Issues
------
-  OASIS-6317
=> Added README.md for generating sphinx docs

MANIFEST.in, docs/source/conf.py, setup.py
This PR ensures that we do not include docs in the packaged SDK.
=> chore(build): Making sure docs is excluded from build

optimizely/entities.py, optimizely/helpers/audience.py, tests/helpers_tests/test_audience.py
Updating audience evaluation log level to be debug. The only info level log will be the one corresponding to the result of overall evaluation of an audience.
=> fix(log-level) Adjusting log level on audience evaluation logs

optimizely/config_manager.py, optimizely/helpers/enums.py, optimizely/optimizely.py, tests/test_config_manager.py, tests/test_optimizely.py
Summary
-------
- Added support for Authenticated Datafiles
- Added new config manager class `(AuthDatafilePollingConfigManager)` that extends `PollingConfigManager` 
- Modify conditional logic in `optimizely.py` to determine the type of config manager that will be used depending on input parameters
Test Plan
-------
- Added tests for `AuthDatafilePollingConfigManager`
- Ran manual tests with a valid access token and corresponding sdk key
=> feat: Added support for Authenticated Datafiles

.travis.yml, README.md, requirements/test.txt
Nose has been in maintenance mode: https://nose.readthedocs.io/en/latest/#note-to-users
Moving to pytest
=> chore: Moving from nose to pytest

optimizely/bucketer.py, optimizely/decision_service.py, optimizely/helpers/audience.py, optimizely/helpers/condition.py, optimizely/helpers/enums.py, tests/helpers_tests/test_audience.py, tests/test_bucketing.py, tests/test_decision_service.py, tests/test_optimizely.py
With this change we are introducing targeted rollout specific log messages. 
Since, rules right now do not have a "name", I am proposing to use rule's index in the log message.
=> fix(logs): Fixing log messages for Targeted Rollouts

optimizely/config_manager.py, tests/test_config_manager.py, tests/test_event_processor.py
Noticed a number of tests were taking a long time. Used the command `pytest --duration=10` to get top 10 slowest tests.
Before:
```
5.01s call     tests/test_event_processor.py::BatchEventProcessorTest::test_drain_on_stop
5.00s call     tests/test_config_manager.py::StaticConfigManagerTest::test_get_config_blocks
3.01s call     tests/test_event_processor.py::BatchEventProcessorTest::test_stop_and_start
3.01s call     tests/test_event_processor.py::BatchEventProcessorTest::test_flush
3.01s call     tests/test_event_processor.py::BatchEventProcessorTest::test_flush_on_mismatch_project_id
3.01s call     tests/test_event_processor.py::BatchEventProcessorTest::test_flush_on_mismatch_revision
3.00s call     tests/test_event_processor.py::BatchEventProcessorTest::test_flush_on_max_timeout
1.76s …
```
=> chore(test): Make unit tests go faster

README.md, optimizely/config_manager.py, optimizely/helpers/enums.py, optimizely/optimizely.py, tests/test_config_manager.py, tests/test_optimizely.py
Summary
----------
- Replaced all instances of `access_token` with `datafile_access_token` to conform to the correct keyword attribute name
Test Plan
----------
- Ran manual tests
=> refactor: replace all instances of access_token w/ datafile_access_token

optimizely/optimizely.py, optimizely/project_config.py, tests/test_optimizely.py
Updating feature evaluation logs so that they apply to both rollouts and experiments
=> fix(logs): Updating feature variable evaluation logs

optimizely/config_manager.py, tests/test_config_manager.py
Summary
-------
We were not catching all exceptions when requesting the datafile. The `HTTPError` class is only a single class of errors and we were not capturing all the other errors like timeout issues, proxy issues, etc.
The class of exceptions can be seen here: https://requests.readthedocs.io/en/master/_modules/requests/exceptions
Updating to catch `RequestException`. It is also something we were already doing correctly in event dispatching: https://github.com/optimizely/python-sdk/blob/master/optimizely/event_dispatcher.py#L42
Test plan
---------
- Tested timeout before and after the fix.
- Unit test added.
=> fix(exception-handling): Catch errors when requesting datafile

README.md, optimizely/config_manager.py, tests/test_config_manager.py
Summary
-------
- https://github.com/optimizely/python-sdk/pull/285 was an incomplete fix; as per [the docs](https://requests.readthedocs.io/en/master/user/quickstart/#timeouts), timeouts and other network errors throw on the call to `.get()`, not on the call to `.raise_for_status()` (`raise_for_status` just checks for a non-2xx HTTP return code; it doesn't handle other kinds of errors)
- This adds additional error handling around calls to `requests.get`.
- Also made a small tweak to the README; `zsh` requires quoting around `.[test]`.
Test plan
---------
- Added unit tests for both the polling config manager and the static config manager
=> fix(exception-handling): Fix handling of network and other non-status-code errors when polling for datafile

optimizely/optimizely_config.py, optimizely/project_config.py, tests/test_optimizely_config.py
Summary
---------
- Updated datafile to ensure that it is being stored and returned as a `string` type instead of previous `bytes` type
Test Plan
---------
- Ran manual tests
Note
-----
- Sohail mentioned that tests were failing in `fullstack_prod_suite` because the `bytes` datafile was not iterable, so I changed it to return a `string`
=> fix: change datafile accessor feature to return a string representation of datafile

.travis.yml
Summary
-------
Stages run sequentially on Travis. If a stage fails, all the following stages are not executed. We execute source clear only on cron, and if due to any reason unit or integration tests fail, the source clear is not executed. Hence, moving source clear stage before tests. 
Test plan
---------
All unit tests must be passed. 
FSC must be passed.
=> ci: Run source clear before linting and tests.

tests/helpers_tests/test_event_tag_utils.py, tests/test_event_processor.py
Summary
-------
- Renames TestEventDispatcher class so that pytest doesn't mistake it for a test class. 
- Replace SimpleLogger from event tag utils test since it's been deprecated.
**Warnings**
```
tests/test_event_processor.py:49
/home/oakbani/Documents/Optimizely/python-sdk/tests/test_event_processor.py:49: PytestCollectionWarning: cannot collect test class 'TestEventDispatcher' because it has a __init__ constructor (from: tests/test_event_processor.py)
class TestEventDispatcher(object):
tests/test_event_processor.py:498
/home/oakbani/Documents/Optimizely/python-sdk/tests/test_event_processor.py:498: PytestCollectionWarning: cannot collect test class 'TestForwardingEventDispatcher' because it has a __init__ constructor (from: tests/test_event_processor.py)
class …
```
=> refact: fix warnings in pytest output

README.md, requirements/core.txt
Summary
-------
jsonschema 3.2.0 has a dependency to pyrsistent>=0.14.0. When PIP tries to install the latest pyrsistent version, it requires Python > 3.5. Therefore, in this PR we explicitly define the version for pyrsistent package. 
Test plan
---------
All checks continue to pass.
=> build: Fix package installation for Python 3.4 and pypy

optimizely/optimizely.py, tests/test_optimizely.py
- sending decision on nil variation
=> sending decision on nil variation

optimizely/event/event_factory.py, optimizely/event/payload.py, optimizely/event/user_event.py, optimizely/event/user_event_factory.py, optimizely/optimizely.py, tests/test_event_factory.py, tests/test_event_payload.py, tests/test_optimizely.py, tests/test_user_event_factory.py
Summary
-------
- This adds 'enabled' field to decision metadata. 
- 'enabled' is set to feature_enabled value for is_feature_enabled and True for activate.
Test plan
---------
- Fixed existing unit tests.
- Manually tested with FSC.
=> feat: added enabled field to decision metadata

CHANGELOG.md, optimizely/version.py, setup.py
Summary
-------
-  decide api - release info: changelog, version bump, py version bump
=> chore: Preparing for 3.8.0 release

.travis.yml, README.md
Summary
-------
Unit tests on Python pypy and pypy3 have been failing consistently for quite some time. On detailed investigation, cryptography package is required by the requests[security] module. Although the latest cryptography version does support pypy, it doesn't build for some reason. 
Setting cryptography package to a static previous version revealed that Python 3.4 support has been dropped after cryptography 2.8.  
Therefore, instead of modifying requirements file, we install the correct working version of cryptography in before_install phase of pyp build. 
Test plan
---------
All checks continue to pass. 
Issues
------
=> ci: Install a compatible version of cryptography for pypy and pypy3 in travis config

CHANGELOG.md, optimizely/version.py
Summary
-------
-  Releasing minor version
- Added support for multiple concurrent prioritized experiments per flag. 
- changes made in https://github.com/optimizely/python-sdk/pull/322
Test plan
---------
- tested with FSC
=> Chore: prepare for 3.8.1 release

optimizely/event/event_processor.py, tests/base.py, tests/test_config.py, tests/test_config_manager.py, tests/test_optimizely.py, tests/test_user_context.py
Summary
-------
- assertRaisesRegexp -> assertRaisesRegex
- assertEquals -> assertEqual
- isAlive() -> is_alive()
- Check added to base.py to confirm attribute assertRaisesRegex for backwards compatibility to Python2.7
Test plan
---------
Compatibility Test
=> Removing deprecated warnings

README.md, requirements/core.txt
Summary
-------
- breaking down module requests[security] into its libraries because requests[security] will no longer be supported with requests version 2.26.
- I unpacked it into libraries: requests, pyOpenSSL, cryptography, idna. Looked for highest versions that work on all Py versions in the SDK (common denominator that works across all Py versions that we support in our SDK)
The “why”, or other context.
Test plan
---------
- FSC compatibility tests passing
Issues
------
-  https://optimizely.atlassian.net/browse/OASIS-7552
=> [OASIS-7552] fix: update requests library dependency

requirements/core.txt
Summary
-------
-  Upgrading Py SDK for dogfooding in the monolith. Part of that is upgrading Pyrsistent lib because the version mismatch causes MOnolith to not start.
- So Pyrsistent in Py SDK importer in monolith and Pyrsistent used in the monolith itself need to match.
Test plan
---------
Issues
------
-  https://optimizely.atlassian.net/browse/OASIS-7808
=> [OASIS-7808] Upgrade pyrsistent to 0.16.0 to match monolith

.flake8, optimizely/bucketer.py, optimizely/decision_service.py, optimizely/project_config.py, tests/test_config.py
Summary
-------
-  Updated changes to use experiment_id_map
-  Build experiment_key_map from experiment_id_map
-  Update decision service to id instead of experiment key
-  Add test cases
Test plan
---------
-  FSC suite
Issues
------
- BugFix
=> Duplicate experiment Key issue with multi feature flag

optimizely/event/user_event_factory.py
Summary
-------
-  Update user_event_factory to use experiment_id when getting variation to fix impression events
Test plan
---------
-  FSC Suite
Issues
------
-  BugFix
=> Fix Impression Events - Variation lookup by id and Experiment id

CHANGELOG.md, optimizely/version.py
Summary
-------
-  Update Changelog to reflect Buxfix
-  Update version to 3.9.1
Preparing for release v3.9.1
Test plan
---------
-  FSC Suite
Issues
------
Bugfix - Fixed issue with serving incorrect variation in projects containing multiple flags with duplicate keys
=> Chore(release): Prepare for v3.9.1 release

optimizely/event/event_processor.py, requirements/core.txt, tests/test_event_processor.py
Summary
-------
-  User reported issue on GitHub: https://github.com/optimizely/python-sdk/issues/352
-  events, dropped from the queue should be logged using a warning or error log level, not debug level
Test plan
---------
- add unit test
- manual reproduction of the issue, fix and manual verification of the fix
- unit tests to pass
- FSC tests to pass
Issues
------
-  https://optimizely.atlassian.net/browse/OASIS-7864
=> [OASIS-7864] fix: update log level from debug to warning

optimizely/optimizely_config.py, tests/test_optimizely_config.py
Summary
-------
-  Update the rollout key to use experiments instead of experiments_map
-  Update tests to have sample delivery rules
Test plan
---------
-  FSC
Issues
------
-  "OASIS-7812"
=> Delivery rules correction for proper rollout key

optimizely/event/event_processor.py
Summary
-------
-  Running event processor would sometimes produce Buffer error with negative timeout interval for retrieving an event from the queue. Reported by a Github user (customer). See https://github.com/optimizely/python-sdk/issues/354 
- If the flushing_interval_deadline is between the first call of _get_time() and the second call of _get_time() then interval will be negative.
Test plan
---------
Unit tests for the _run() function where the change is made already extensively cover the _run() and event processor functionality. 
The change itself should prevent negative interval from occurring. To test that a larger load test would be required. 
Issues
------
-  https://optimizely.atlassian.net/browse/OASIS-7872
=> [OASIS-7827] fix: make _get_time() value the same throughout the loop

optimizely/optimizely_config.py
Summary
-------
-  Deprecate experiments_map for OptimizelyFeature
-  Note added for experiments_map in OptimizelyConfig stating it is for legacy projects only
OptimizelyFeature experiments_map is deprecated, users shall use experiment_rules and delivery_rules.
Test plan
---------
- FSC
Issues
------
- N/A
=> Add deprecation notes for OptimizleyConfigV2

optimizely/bucketer.py, requirements/core.txt, tests/test_bucketing.py
Summary
-------
-  Removal of mmh3 external dependency and update imports to use internal pymmh3 instead
Testing
-------
- FSC
Issues
-------
- "OASIS-7995"
=> enhancement: Remove mmh3 external dependency and use internal pymmh3 in place

optimizely/decision_service.py, optimizely/project_config.py, tests/test_decision_service.py
- Removed `get_variation_from_experiment_rule` and `get_variation_from_delivery_rule` from decision service. 
- `flag_variations_map` logic improved using existing loops and removed `get_all_variations_for_each_rule`.
- Unit test fixed.
All FSC and unit tests should pass
=> Refact: Refactored Forced decision

optimizely/event/user_event_factory.py, optimizely/project_config.py, tests/test_event_factory.py, tests/test_user_context.py, tests/test_user_event_factory.py
Summary
-------
-  Crash fixed after logging syntax correction
-  Updated order for checking variation in impression event
- Unit test added for no active experiment in creating impression event
- Unit test fixed after changes
Test plan
---------
- All unit tests and FSC should pass.
=> fix: Forced variation not available in experiment

optimizely/decision_service.py, optimizely/optimizely.py, optimizely/optimizely_user_context.py
Summary
-------
- `find_validated_forced_decision` moved to decision service.
Test plan
---------
- All unit tests and FSC should pass.
=> refactor: moved validated forced decision to decision service

.travis.yml, requirements/core.txt, requirements/test.txt, setup.py, tests/helpers_tests/test_condition.py, tests/helpers_tests/test_validator.py, tests/test_optimizely.py
Summary
-------
-  Old python versions for Py SDK are causing security risks and cap using more up to date library versions. This creates issues for customers. 
For example we removed Py v3.4 already because PyYaml library in Py 3.4 can only be less than v5.4 which doesn't have a necessary security patch that versions 5.4 and greater do.
Another example is customer issue [issue link here] that required more up to date jsonschema lib version. But we could not provide that up to date version because Py 2.7 and 3.5 were capping it. See issue [370](https://github.com/optimizely/python-sdk/issues/370)
These are all issues related to supporting older Py versions that only work with libraries up certain version number. So we get a discrepancy between which library versions old Py and new Py …
=> chore: remove old py versions

CHANGELOG.md, optimizely/version.py
Summary
-------
-  Prepare for release 3.11.0
Test plan
---------
- Travis CI Tests
Issues
------
-  https://optimizely.atlassian.net/browse/OASIS-7933
=> chore: Prepare for release 4.0.0

optimizely/optimizely.py
Summary
-------
-  log for error when flag key is invalid produced incorrect log message. String formatting issue.
- this is now corrected
=> Fix formatting of the error log for flag key

tests/test_config_manager.py, tests/test_user_context.py
Summary
-------
-  Fix forced decision test with thread safe call counter
-  Fix polling config manager tests from interfering with their own results
-  Add wrapper class to allow actual testing of the polling thread
Due to a difference in the way pypy implements threading, tests utilizing threading have been intermittently failing the pypy CI. For the polling config manager, depending on when the polling thread started, it would sometimes poison the results, due to the mock library not interacting with the thread correctly.
For the forced decision test, mock's call_count is not thread safe, so the calls were sometimes not counted correctly.
Additionally, some of the polling config manager tests were calling fetch_datafile manually and then confirming that the polling thread was still …
=> fix: tests that utilize threading from failing with pypy

.github/workflows/python.yml, mypy.ini, optimizely/entities.py, optimizely/event/event_processor.py, optimizely/event_dispatcher.py, optimizely/helpers/types.py, optimizely/logger.py, optimizely/notification_center.py, optimizely/optimizely.py, optimizely/optimizely_config.py, optimizely/optimizely_user_context.py, requirements/typing.txt, tests/test_optimizely.py
Summary
-------
-  Add type hints to the public interface of SDK.
-  Add mypy check to github actions
-  Additional type hints to be submitted in second PR
Allows automatic static type checking to prevent bugs as well as type hints for users of the SDK. Remaining type hints will be added in subsequent PR. At that time, we can enable mypy --strict, enforcing type hinting going forward.
=> refactor: type hints public interface

optimizely/odp/__init__.py, optimizely/odp/lru_cache.py, tests/test_lru_cache.py
Summary
-------
Add a generic LRU cache to support efficient caching of the ODP segments results. 
- Add Least Recently Used (LRU) cache
- design to allow developer to pass in different caching implementation. Provide default.
Test plan
---------
Added:
- test_lru_cache.py
Ticket:
---------
[OASIS-8404](https://optimizely.atlassian.net/browse/OASIS-8404)
=> feat: add lru cache

optimizely/event_dispatcher.py, optimizely/helpers/enums.py, optimizely/odp/zaius_graphql_api_manager.py, optimizely/optimizely.py, tests/test_event_dispatcher.py, tests/test_odp_zaius_graphql_api_manager.py
Summary
-------
- Adding a REST API to fetch audience segments from ODPs GraphQL service: zaius_graph_ql_api_manager.py
- Per Jira ticket [OASIS-8403](https://optimizely.atlassian.net/browse/OASIS-8403)  
- Acceptance criteria in the ticket:
>* Endpoint: https://api.zaius.com/v3/graphql
>* See TDD for details (request and response formats) and sample calls.
>* When fetching is completed successfully, it should return valid segments (string array). An empty array is a valid segment set.
>* When fetching fails, it should return a null segments array with the error logged (and/or returned).
>* When the server returns the “InvalidIdentifierException” error, this specific reason should be logged (and/or returned). Other errors can be logged (and/or returned) as “fetchSegmentsFailed”.
Test plan …
=> (feat) add zaius graphql api manager w tests

tests/test_odp_zaius_graphql_api_manager.py
Summary
-------
-  add missing license
- [OASIS-8403 add ODP GraphQLApi interface](https://optimizely.atlassian.net/browse/OASIS-8403)
Test plan
---------
unit tests
=> Add license notice to graphgl test file

optimizely/odp/zaius_graphql_api_manager.py, tests/test_odp_zaius_graphql_api_manager.py
Summary
-------
-  Add additional validation to ODP GraphQL json encoding
-  change log level to warning for invalid identifier
- part of ticket [OASIS-8403 add ODP GraphQLApi interface](https://optimizely.atlassian.net/browse/OASIS-8403)
Test plan
---------
- adjusted unit tests
- FSC tests
=> feat: add json encoding validation

.github/workflows/python.yml, tests/base.py
Summary
-------
This changes are part of the ticket to cleanup and put in orer Python language versions (see ticket below).
-  remove last reference to Python 2.7 (2 lines in tests/base.py)
- upgrade py version to 3.10 in gitactions linting
Test plan
---------
- passing unit tests 
- passing FSC tests
- passing linting
Issues
------
-  [OASIS-8470 Update Supported Language Version](https://optimizely.atlassian.net/browse/OASIS-8470)
=> update py version to 3.10 for  gitactions linting

optimizely/helpers/enums.py, optimizely/helpers/validator.py, optimizely/odp/odp_config.py, optimizely/odp/odp_event.py, optimizely/odp/odp_event_manager.py, optimizely/odp/zaius_rest_api_manager.py, tests/base.py, tests/test_odp_event_manager.py
Summary
-------
OdpEventManager provides internal services for sending ODP events to the ODP server. 
- adds default values to identifiers and data fields for all events.
- stores requested events if they cannot be sent to the server.
- stored events are dispatched when resources are available.
Test plan
---------
- added test_odp_event_manager.py
Ticket
------
[OASIS-8442](https://optimizely.atlassian.net/browse/OASIS-8442)
=> feat: add odp event manager

.github/workflows/ticket_reference_check.yml, tests/test_odp_zaius_rest_api_manager.py
Summary
-------
-  An addition of custom JSON encoder in OdpEvent and ZaiusRestApiManager required the ZaiusrestApi tests to be updated.
- Changed event payload from dicts to instances of OdpEvent class.
- One test needed to be updated.
Test plan
---------
- passing unit tests
Issues
------
-  [FSSDK-8447](https://jira.sso.episerver.net/browse/FSSDK-8447 )
=> chore: update tests because of custom json encoder

optimizely/odp/odp_event_manager.py, optimizely/odp/odp_manager.py, optimizely/odp/odp_segment_manager.py, tests/test_odp_event_manager.py, tests/test_odp_manager.py, tests/test_odp_segment_manager.py
Summary
-------
-  remove odp_config from contructors for odp event manager and odp segment manager
Test plan
---------
all tests pass
Ticket
------
- [OASIS-8405](https://jira.sso.episerver.net/browse/FSSDK-8405)
- [OASIS-8442](https://jira.sso.episerver.net/browse/FSSDK-8442)
=> refactor: remove odp config from constructors

optimizely/optimizely_user_context.py, tests/test_user_context.py
Summary
-------
-  Skip sending identify user event to odp when user_context is cloned.
Prevents duplicate identify calls from being made.
Test plan
---------
added test to test_user_context.py
Ticket
------
[FSSDK-8478](https://jira.sso.episerver.net/browse/FSSDK-8478)
=> fix: skip identify on user_context clone

optimizely/config_manager.py, optimizely/optimizely.py, requirements/typing.txt, tests/test_config_manager.py
Summary
-------
- Add stop method to PollingConfigManager
- Stop PollingConfigManager from Optimizely.close()
- Fix Optimizely docstring to say BatchEventProcessor is the default
- Lock mypy to version 0.982 due to regression
Test plan
---------
fixed tests
Ticket
------
[FSSDK-8499](https://jira.sso.episerver.net/browse/FSSDK-8499)
=> feat: add stop method to polling config manager

optimizely/config_manager.py, optimizely/helpers/constants.py, optimizely/helpers/enums.py, optimizely/notification_center_registry.py, optimizely/optimizely.py, tests/base.py, tests/test_config.py, tests/test_config_manager.py, tests/test_notification_center_registry.py, tests/test_optimizely.py, tests/test_optimizely_config.py, tests/test_optimizely_factory.py
Summary
-------
Create a private registry of NotificationCenters for internal use.
- Remove dependence on user supplied NotificationCenter.
- Resolve issue of notifications being registered with one NotificationCenter and sent to a different one.
Test plan
---------
added tests to
- test_notification_center_registry.py
- test_optimizely.py
- test_optimizely_config.py
- test_optimizely_factory.py
Ticket
------
[FSSDK-8773](https://jira.sso.episerver.net/browse/FSSDK-8773)
=> fix: add notification center registry

optimizely/optimizely.py, optimizely/optimizely_user_context.py, tests/test_notification_center_registry.py, tests/test_optimizely.py, tests/test_user_context.py
Summary
-------
-  make fetch_qualified_segments, identify_user, setup_odp private methods in Optimizely
Test plan
---------
existing tests should pass
Ticket
------
- [FSSDK-8478](https://jira.sso.episerver.net/browse/FSSDK-8478)
=> fix: make client odp methods private

optimizely/optimizely.py, tests/test_optimizely.py
Summary
-------
-  Updated send_odp_events to require identifiers and contain at least one key
Test plan
---------
- updated test_optimizely.py
Ticket
------
-  [FSSDK-8946](https://jira.sso.episerver.net/browse/FSSDK-8946)
=> [FSSDK-8946] fix: make odp event identifiers required

README.md, setup.py
Summary
-------
-  Updates readme and setup.py replacing Full Stack with Feature Experimentation
Test plan
---------
All tests should pass.
Ticket
------
[FSSDK-8954](https://jira.sso.episerver.net/browse/FSSDK-8954)
=> [FSSDK-8954] docs: change full stack to feature experimentation

CHANGELOG.md, optimizely/version.py
Summary
-------
-  Prepare for 4.1.1 release
Ticket
------
[FSSDK-8954](https://jira.sso.episerver.net/browse/FSSDK-8954)
=> [FSSDK-8954] chore: prep for 4.1.1 release

.gitignore, optimizely/optimizely.py, tests/test_optimizely.py
Summary
-------
- Added blocking call to `Optimizely._identify`, `Optimizely._fetch_qualified_segments` and `Optimizely.send_odp_event` to ensure datafile has been downloaded before attempting to make odp requests.
Test plan
---------
all existing tests pass
=> fix: block odp methods on datafile

optimizely/helpers/enums.py, optimizely/odp/odp_event.py, optimizely/optimizely.py, tests/test_odp_event_manager.py, tests/test_optimizely.py
Summary
-------
Add validation to send_odp_events:
- log error when action == None or ""
- use default when type == None or ""
- fix case and/or "-" for `fs_user_id` identifier key
Test plan
---------
added tests to:
test_odp_event_manager.py
test_optimizely.py
Ticket
------
[FSSDK-9069](https://jira.sso.episerver.net/browse/FSSDK-9069)
=> [FSSDK-9069] fix: odp event validation

.github/workflows/python.yml
Summary
-------
- Removes support for python version 3.7 and adds test support for 3.11
Test plan
---------
- All tests should pass
Ticket
------
[FSSDK-9098](https://jira.sso.episerver.net/browse/FSSDK-9098)
=> [FSSDK-9098]: Updates minimum python version for CI Tests to 3.8

optimizely/config_manager.py
Summary
-------
-  Implements a warning log for polling interval below 30s
Test plan
---------
- All tests should pass
Issues
------
-  -  [FSSDK-9510](https://jira.sso.episerver.net/browse/FSSDK-9510)
=> [FSSDK-9510]: Implements a warning log for polling interval below 30s

optimizely/config_manager.py, tests/test_config_manager.py
Summary
-------
-  Update error log message, make it more accurate
Test plan
---------
Issues
------
-  [FSSDK-10064](https://jira.sso.episerver.net/browse/FSSDK-10064)
=> Mpirnovar update error

requirements/core.txt
Summary
-------
PyOpenSSL and cryptography packages are no longer required and can potentially introduce a security risk as pointed out by PeterJCLaw in his reported [GitHub issue](https://github.com/optimizely/python-sdk/issues/434).
Sdk used to use requests extra option requests[security] that included PyOpenSSL and cryptography packages to enhance SSL/TLS support, particularly for older versions of Python that lacked certain security features.
The requests[security] extra was officially deprecated in version 2.25.0 of the requests library, released on November 11, 2020. The deprecation notice indicated that this extra would be removed in version 2.26.0. The primary reason for deprecation was the improved native SSL/TLS support in modern Python versions, making the extra dependencies …
=> [FSSDK-10317] Remove PyOpenSSL and cryptography from requirements

README.md
Summary
-------
-  Addition to https://github.com/optimizely/python-sdk/pull/435 
- removing mentions of license dependencies for PyOpenSSL and cryptography
Test plan
---------
No code change involved. All tests passing.
Issues
------
-  https://jira.sso.episerver.net/browse/FSSDK-10317
=> [FSSDK-10317] Remove dependency mentions in README

optimizely/decision_service.py, optimizely/optimizely.py, optimizely/user_profile.py, tests/test_decision_service.py, tests/test_optimizely.py, tests/test_user_context.py, tests/test_user_profile.py
Summary
-------
- Currently, decideForKeys loops over the list of flags and calls decide for each, which in turn calls ups. So for decideForKeys, there is two calls per flag to UPS. This PR batches UPS calls when using decideForKeys.
Test plan
---------
- Existing tests are updated to work with the new change. New tests will be added for batching.
Issues
------
-  FSSDK-10763
=> [FSSDK-10763] Implement UPS request batching for decideForKeys

CHANGELOG.md, optimizely/version.py
Summary
-------
-  Prep for patch release 5.1.0
-  Updated changelog
-  Update version
Issues
------
-  [FSSDK-10846](https://jira.sso.episerver.net/browse/FSSDK-10846)
=> [FSSDK-10846] chore: prepare for 5.1.0 release

tests/testapp/application.py
Summary
-------
-  PRISMA is complaining about CSRF protections being disabled in a unit test for a flask app. While not really a vulnerability, good to show proper security even in an example/test. So update to enable CSRF.
Test plan
---------
Run tests.
Issues
------
-  [FSSDK-11362](https://jira.sso.episerver.net/browse/FSSDK-11362)
=> [FSSDK-11362] Fix CSRF security warning

optimizely/entities.py, optimizely/helpers/types.py, optimizely/project_config.py, tests/test_config.py
Add cmab experiment properties to project config
- added unit test for cmab field
[FSSDK-11139](https://jira.sso.episerver.net/browse/FSSDK-11139)
=> [FSSDK-11139] update: enable project config to track CMAB properties

tests/testapp/application.py
Summary
-------
- Prisma is (still) not happy with our test app because lack of CSRF protection.
- This adds a secret key, in hopes this will make prisma happy.
Test plan
---------
- Merge to master, see if prisma is ok with it.
- This is just a sample app, not much to test here.
Issues
------
-  [FSSDK-11362](https://jira.sso.episerver.net/browse/FSSDK-11362)
=> [FSSDK-11362] Try 3 to fix prisma scan issue with CSRF

.flake8, optimizely/optimizely.py, optimizely/project_config.py, tests/test_user_context.py
**Summary**
----------
- Added `experiment_id` and `variation_id` to the decision notification listener payload in the Python SDK.
- Ensured that these IDs are included in all decision notifications sent via the notification center.
- Updated unit tests to validate the presence of `experiment_id` and `variation_id` in the payload.
**Why**
-------
To support data warehouse-native customers who rely on SDK notification listeners to send experiment data to their data warehouse, we need to include `experiment_id` and `variation_id` in the payload. This ensures that the stats engine can correctly compute experiment results based on warehouse data.
**Test Plan**
------------
- Modify existing or add unit tests to check for the presence of `experiment_id` and `variation_id` in the notification …
=> [FSSDK-11017] update: experiment_id and variation_id added to payloads

optimizely/odp/lru_cache.py, tests/test_lru_cache.py
Summary
-------
Added remove method in LRU cache class
Test plan
---------
Added unit tests
Issues
------
[FSSDK-11157](https://jira.sso.episerver.net/browse/FSSDK-11157)
=> [FSSDK-11157] update: add remove method in LRU Cache for CMAB service

optimizely/cmab/cmab_client.py, optimizely/exceptions.py, optimizely/helpers/enums.py, tests/test_cmab_client.py
Summary
-------
- Implemented DefaultCmabClient, a client for fetching CMAB (Contextual Multi-Armed Bandit) decisions.
- Supports configurable retries with exponential backoff through CmabRetryConfig.
- Handles error scenarios such as network failures, non-2xx responses, invalid JSON, and malformed responses.
- Logs relevant error and retry information using the Optimizely logger.
Test plan
---------
- Created unit tests for checking various scenarios.
Issues
------
-  [FSSDK-1148](https://jira.sso.episerver.net/browse/FSSDK-11148)
=> [FSSDK-11148] update: Implement CMAB Client
